### ISSUE TITLE
Sign Up link not working on Membership page

### ISSUE THREAD

**Issue by YannickMol** [CodyHouse/cd-saturno-changelog#1]
Hi both, 

The Saturno template is looking goooood, well done! 
One remark: the sign up button is not working on the [membership page](https://codyhouse.co/demo-templates/saturno/membership.html), hope you can fix this!

**Comment by sebastiano-guerriero** [comment]
Hi! Thanks for the heads-up! We've pushed an updated version that includes the checkout process 👍
